pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          subject: "(Pipeline Notification – Pipeline <+pipeline.name> | Status <+pipeline.status> | Stage <+stage.name>| Stage <+stage.status>)"
                          body: |-
                                    Hi <+pipeline.variables.techLeadName>,<br/>                 
                                    The pipeline <strong><+pipeline.name></strong> has completed with status **<+pipeline.status>** <br/>
                                    <p><strong>Status:</strong> <+pipeline.status><br/>
                                    <strong>Triggered By:</strong> <+pipeline.triggeredBy.name><br/>
                                    <strong>Build Number:</strong> <+pipeline.sequenceId><br/>
                                    <strong>Branch:</strong> <+pipeline.sourceBranch><br/>         
                                    <strong>End Time:</strong> <+pipeline.endTs> <br/>
                                    <strong>Duration:</strong> <+pipeline.durationMs><p><br/>
                                    <+pipeline.name> <+pipeline.triggeredBy.name>            
                                    hi <+pipeline.name> sttaus <+pipeline.triggeredBy.name>
                                    <p>You can review the build and deployment details here:<br/><+pipeline.executionUrl><br/>
                                    Thank you for your continued efforts!</p>
                                    <+ (<+pipeline.status> == "SUCCEEDED"){ return "The pipeline **<+pipeline.name>** completed success.": " The pipeline **<+pipeline.name>** completed fail."}>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testconn
        repoName: cx_sync
        build: <+input>
