pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: final
        identifier: final
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Hello World"
                          echo var test
                    environmentVariables: []
                    outputVariables:
                      - name: test
                        type: String
                        value: Ali
                  timeout: 10m
            rollbackSteps: []
          services:
            values:
              - serviceRef: failure2
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      manifests:
                        - manifest:
                            identifier: mainq
                            type: Kustomize
                            spec:
                              store:
                                type: HarnessCode
                                spec:
                                  repoName: <+input>
              - serviceRef: testschwab
              - serviceRef: nginx
            metadata:
              parallel: false
          environment:
            environmentRef: testforever
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testforever
        tags: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
