pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: "<+ if (<+pipeline.status> == \"SUCCEEDED\"){ return \"The pipeline **<+pipeline.name>** completed success.\": \" The pipeline **<+pipeline.name>** completed fail.\"}>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: testconn
        repoName: cx_sync
        build: <+input>
