pipeline:
  name: demoO
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: test
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Hello World"
                          cd dance
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsSuccess
    - stage:
        name: run
        identifier: run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: prod
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Background
                  name: dind
                  identifier: dind
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:25.0.4
                    shell: Sh
                    privileged: true
                contextType: Pipeline
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:25.0.4
                    shell: Sh
                    command: |-
                      cat > Dockerfile <<'EOF'
                      FROM amazoncorretto:17-alpine
                      RUN uname -m
                      RUN java -version
                      EOF

                      echo "Dockerfile created:"
                      cat Dockerfile
                    privileged: true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: test
                    tags:
                      - multiarch-test
                    caching: true
                    envVariables:
                      PLUGIN_PLATFORM: linux/amd64,linux/arm64
                      PLUGIN_BUILDER_DRIVER: docker-container
                    baseImageConnectorRefs:
                      - account.harnessImage
          sharedPaths:
            - /var/run
            - /var/lib/docker
        delegateSelectors:
          - noah-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
    - stage:
        name: test0
        identifier: test0
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: tst
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tst
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |+
                          #!/usr/bin/env bash
                          set -euo pipefail

                          echo "=== Secret resolution test started ==="

                          SECRET_VALUE='<+secrets.getValue("special-character")>'

                          echo "Secret resolved successfully"

                          echo "Secret length:"
                          echo "${#SECRET_VALUE}"

                          ENCODED=$(printf '%s' "$SECRET_VALUE" | base64)
                          echo "Base64 encoding succeeded"

                          DECODED=$(printf '%s' "$ENCODED" | base64 --decode)

                          if [[ "$DECODED" == "$SECRET_VALUE" ]]; then
                            echo "Round-trip encode/decode: OK"
                          else
                            echo "Round-trip encode/decode: FAILED"
                            exit 1
                          fi

                          echo "=== Secret test completed successfully ==="

                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          services:
            values: <+input>
            metadata:
              parallel: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  properties:
    ci:
      codebase:
        repoName: test
        build: <+input>
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: PipelineStart
        - type: PipelineFailed
        - type: PipelineSuccess
        - type: PipelineEnd
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - noah.unor99@gmail.com
      enabled: true
      template:
        versionLabel: v1
        templateRef: test
        orgIdentifier: default
        projectIdentifier: bootcampcinoahunor
