pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubconnector
        repoName: cx_sync
        build: <+input>
  stages:
    - stage:
        name: demo
        identifier: demo
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.testk8s
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: library/nginx
                    shell: Bash
                    command: echo "Hello World"
                    outputVariables:
                      - name: PLUGIN_DRY_RUN
                        type: String
                        value: "true"
