pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubconnector
        repoName: cx_sync
        build: <+input>
  stages:
    - stage:
        name: final
        identifier: final
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          services:
            values:
              - serviceRef: nginx
              - serviceRef: init_instance
              - serviceRef: testschwab
            metadata:
              parallel: true
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello World"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: test
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: testdgenv
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: testforever
                deployToAll: true
                infrastructureDefinitions: <+input>
        tags: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
