pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testing
        identifier: testing
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: testforever
            deployToAll: false
            infrastructureDefinitions:
              - identifier: testforever
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #!/bin/bash

                          set -e

                          env_type=<+env.type>

                          echo "pipeline.triggerType:  <+pipeline.triggerType>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
