pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: test
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Hello World"
                          cd dance
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsSuccess
    - stage:
        name: run
        identifier: run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: prod
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine:3.19
                    shell: Sh
                    command: |-
                      cat > Dockerfile <<'EOF'
                      FROM nginx:stable-alpine
                      RUN echo "hello multiarch" > /usr/share/nginx/html/index.html
                      EOF

                      echo "Dockerfile created:"
                      cat Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: test
                    tags:
                      - multiarch-test
                    caching: true
                    envVariables:
                      PLUGIN_PLATFORM: linux/amd64,linux/arm64
                      PLUGIN_BUILDER_DRIVER: docker-container
  properties:
    ci:
      codebase:
        repoName: test
        build: <+input>
