pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy via Matrix
        identifier: Deploy_via_Matrix
        type: Deployment
        strategy:
          matrix:
            include: <+input>
            maxConcurrency: <+input>.default(2)
            nodeName: deploy_<+matrix.service>_to_<+matrix.environment>_<+matrix.infrastructure>
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+matrix.service>
          environment:
            environmentRef: <+matrix.environment>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: <+matrix.infrastructure>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Echo
                  identifier: Echo
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Service=<+matrix.service>"
                          echo "Env=<+matrix.environment>"
                          echo "Infra=<+matrix.infrastructure>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
