pipeline:
  name: demo
  identifier: demo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: prod
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: RestoreCacheS3
                  name: RestoreCacheS3_1
                  identifier: RestoreCacheS3_1
                  spec:
                    connectorRef: account.AWS_Connector
                    region: us-east-1
                    bucket: noah-cur-test
                    key: cache-test-dns-{{ checksum "package.json" }}
                    archiveFormat: Tar
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  properties:
    ci:
      codebase:
        repoName: test
        build: <+input>
