pipeline:
  name: test-cascading_secrets
  identifier: testcascading_secrets
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: step secret no stage template
        identifier: step_secret_via_stage_template
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: tst
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: tst
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tst
          execution:
            steps:
              - step:
                  name: test
                  identifier: test
                  template:
                    templateRef: test_cascading_secrets
                    versionLabel: v1
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: step secret via stage templates
        identifier: step_secret_via_stage_templates
        tags: {}
        template:
          templateRef: test_cascading_secret1
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
            variables:
              - name: secretInput
                type: Secret
                value: <+input>
