pipeline:
  name: test-BGdemo
  identifier: testBGdemo
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: nginx
        identifier: nginx
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginx
          environment:
            environmentRef: test
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        variables:
          - name: name
            type: String
            description: ""
            required: false
            value: bg-demo
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
