pipeline:
  name: tst
  identifier: tst
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tst
        identifier: tst
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: tst
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: tst
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tst
          execution:
            steps:
              - step:
                  name: Test Bug
                  identifier: Test_Bug
                  template:
                    templateRef: testHTTP
                    versionLabel: v1
                    templateInputs:
                      type: Http
                      spec:
                        inputVariables:
                          - name: message
                            type: String
                            value: Some message with one plain variable <+pipeline.name>
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: tst
            type: String
            description: ""
            required: false
            value: <+stage.variables.VARIABLE_NAME>
