pipeline:
  name: trigger-pipeline
  identifier: triggerpipeline
  projectIdentifier: bootcampcinoahunor
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ppipeline-trigger
        identifier: tst
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: account.AA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tst
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello World"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
