name: <+stage.variables.VARIABLE_NAME>
replicas: 2

image: <+artifacts.primary.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 80

env: 
  config:
    key1: value10
  secrets:
    ACCESS_KEY: '<+secrets.getValue("account.<+env.identifier>AccessKey")>'
    
